language: r
cache: packages

r_packages:
  - testthat
  - knitr

r_github_packages:

before_script:
  - Rscript -e "pureseqtmr::install_pureseqtm()"

script:
  - travis_wait 120 Rscript scripts/run.R

after_success:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

